version: "3"

services:
    nginx:
        image: nginx:alpine
        working_dir: /application
        volumes:
            - ./sites/nginx:/etc/nginx/conf.d
            - ./www:/application
        networks:
            - lnmp
        # links:
        #     - php
        expose:
            - "80"
        ports:
            - "80:80"
    php:
        image: phpdockerio/php73-fpm
        working_dir: /application
        volumes:
            # - ./sites/php7.3/php.ini:/etc/php/7.3/fpm/php.ini
            - ./www:/application
        networks:
            - lnmp
        # links:
        #     - mariadb
        #     - redis
        #     - memcached
        #     - mongo
        expose:
            - "9000"
    mariadb:
        image: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./data/mariadb:/var/lib/mysql
        networks:
            - lnmp
        expose:
            - "3306"
        ports:
            - "3306:3306"
    redis:
        image: redis
        volumes:
            - ./data/redis:/data
        networks:
            - lnmp
        ports:
            - "6379:6379"
        # expose: # expose暴露容器给link到当前容器的容器
        #    - "6379"
    memcached:
        image: memcached
        networks:
            - lnmp
        expose:
            - "11211"
    mongo:
        image: mongo
        networks:
            - lnmp
        restart: always
        volumes:
            - ./data/mongo:/data
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
        expose:
            - "27017"

    mongo-express:
        image: mongo-express
        networks:
            - lnmp
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: root

networks:
    lnmp: