version: "1"

services:
    nginx:
        image: nginx
        volumes:
            - ./sites:/etc/nginx/conf.d
            - ./www:/www
        networks:
            - lnmp
        depends_on:
            - php
        expose:
            - "80"
        ports:
            - "80:80"
    php:
        image: registry.cn-shenzhen.aliyuncs.com/yansongda/php-fpm
        volumes:
            - ./www:/www
        networks:
            - lnmp
        depends_on:
            - mariadb
            - redis
            - memcached
            - mongo
        expose:
            - "9000"
    mariadb:
        image: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./data/mariadb:/var/lib/mysql
        networks:
            - lnmp
        expose:
            - "3306"
        ports:
            - "3306:3306"
    redis:
        image: redis
        volumes:
            - ./data/redis:/data
        networks:
            - lnmp
        expose:
            - "6379"
    memcached:
        image: memcached
        networks:
            - lnmp
        expose:
            - "11211"
    mongo:
        image: mongo
        restart: always
        volumes:
            - ./data/mongo:/data
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: root
    
    tools:
        image: registry.cn-shenzhen.aliyuncs.com/yansongda/tools
        volumes:
            - ./www:/www
        networks:
            - lnmp

networks:
    lnmp:
